### PR TITLE
Fix broken spec

### PR DESCRIPTION
**Pull request by sobrinho**

### CODE REVIEW

**Comment by sobrinho** [comment]
@bf4 ping

**Comment by sobrinho** [comment]
@bf4 btw, if you want a maintainer, I can maintain this one ;)

**Comment by bf4** [comment]
Sorry I didn't see this. Until Sidekiq 7.0 is released and this code is fully removed from it, my intention is that the code in it be the same, or least include it exactly. In what sense is a spec broken? It looks like you changed the code, not a spec.

**Comment by bf4** [comment]
Breaks tests and contract. I'll accept a new PR to update it from [6.4.1](https://github.com/gemhome/sidekiq-delay_extensions/tree/v6.4.1) to https://rubygems.org/gems/sidekiq 6.4.2 then 6.5.0 then 6.5.1

**Comment by sobrinho** [comment]
@bf4 not sure why CI on master is green but it's not on master, you have a explicit spec for this: https://github.com/gemhome/sidekiq-delay_extensions/blob/main/test/test_extensions.rb#L28-L36

**Comment by sobrinho** [comment]
Screen Shot 2022-08-04 at 07 19 20

**Comment by bf4** [comment]
hmm, on main da25e46cdf4247139bf70aecb045b8e964fd9b8e tests pass for me with ruby 2.7.2 and ruby 3.0.3

on v6.4.1 tests pass for me with both ruby 2.7.2 and 3.0.3

Also, I've been using this in production with Ruby 3.0.3

I'm not sure what's causing your failure

**Comment by sobrinho** [comment]
That's funny since there is no code stringifying the keys: https://github.com/gemhome/sidekiq-delay_extensions/blob/da25e46cdf4247139bf70aecb045b8e964fd9b8e/lib/sidekiq/delay_extensions/generic_proxy.rb#L13

Would you add some debugging there to see why it's passing in your local machine? Or maybe create a branch with an empty commit to see the CI behavior?

**Comment by sobrinho** [comment]
And note that Sidekiq did that recently: https://github.com/mperham/sidekiq/commit/5bfaeea73ad939f95dfa362c1f939e6168c590cb

**Comment by bf4** [comment]
Ok. You understand that this gem is extracted from sidekiq as a one to one?  So, that change in 6.5.3 will land here when we extract 6.5.3. 

If there's a bug in this code, it's a bug in sidekiq. But I can't duplicate your failure running the test suite here or in the sidekiq repository with the information you provided

**Pull request closed without merging**
