### PR TITLE
Add safe_load for Sidekiq 7 compatibility

### PR DESCRIPTION
**Pull request by sobrinho**
Fixes https://github.com/gemhome/sidekiq-delay_extensions/issues/8

### CODE REVIEW

**Comment by NielsKSchjoedt** [comment]
Bump :-)

**Comment by sobrinho** [comment]
I have been running this on production since August 🤷

**Comment by joevandyk** [comment]
any reason to not merge?

**Comment by bf4** [comment]
I'll take a closer look. Sorry for the delay.

**Comment by bf4** [comment]
> any reason to not merge?

Yes, we won't be replacing safe load with unsafe load

**Comment by bf4** [comment]
Take a look at https://github.com/gemhome/sidekiq-delay_extensions/issues/9#issuecomment-1743489763 and https://github.com/gemhome/sidekiq-delay_extensions/pull/14#discussion_r1343002710 for the patches I have in my app on latest Sidekiq 7.  

I'm going to start working through these https://github.com/gemhome/sidekiq-delay_extensions/issues/4

**Comment by bf4** [comment]
Working on a 7.0 branch now https://github.com/gemhome/sidekiq-delay_extensions/pull/22

(For context, I've been running on this gem version 6.4.1 and am on sidekiq 7.2.0 with patches and Rails 7.0)

**Comment by bf4** [comment]
Sorry for the delay on this. I wasn't going to make any patches to the Sidekiq 6.x series work until we'd reach Sidekiq 7.x parity.  And I've now release 7.0 https://github.com/gemhome/sidekiq-delay_extensions/pull/22 👯 But again sorry for the delay and thanks for the poking.

**Pull request closed without merging**
